# Base configs
baseurl: ""
url: "http://lenarori.github.io/"
image_fulls_loc: "images/fulls"
image_thumbs_loc: "images/thumbs"
#google_analytics: ""

# UI configs
title: "Photography by R. Calen Walshe"
subtitle: "See the world through my eyes!"
author: "R. Calen Walshe"
bio: "Lena and Rori are sister and they are also best friends."
publicise: "Blah blah"
web_design: "RCW"
social_urls:
  instagram: "https://www.instagram.com/lenarori"
