# Base configs
baseurl: ""
url: "http://lenarori.github.io/"
image_fulls_loc: "images/fulls"
image_thumbs_loc: "images/thumbs"
#google_analytics: ""

# UI configs
title: "Photography by R. Calen Walshe"
author: "R. Calen Walshe"
subtitle: ""
bio: "Watch Lena and Rori storm through the world."
social_urls:
  instagram: "https://www.instagram.com/ramswarooppatra"
  
